/**
 * Sample React Native App
 *
 * adapted from App.js generated by the following command:
 *
 * react-native init example
 *
 * https://github.com/facebook/react-native
 */

import React, {Component} from 'react';
import {Button, Image, StyleSheet, Text, View} from 'react-native';
import PhotoPicker from 'react-native-photo-picker';

export default class App extends Component {
  state = {
    error: null,
    imageURL: null,
  };

  render() {
    return (
      <View style={styles.container}>
        <Button title="Choose Image" onPress={this.choosePhoto} />

        {this.state.error && <Text>Error: {this.state.error}</Text>}
        {this.state.imageURL && (
          <>
            <Image
              style={{width: 300, height: 200}}
              source={{uri: this.state.imageURL}}
            />
            <Text>Image URL: {this.state.imageURL}</Text>
          </>
        )}
      </View>
    );
  }

  choosePhoto = () => {
    PhotoPicker.choosePhotoWithOptions({}, (error, imageURL) => {
      console.warn({error, imageURL});
      this.setState({
        status: 'native callback received',
        error,
        imageURL,
      });
    });
  };
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
